from django.http import HttpResponse
from django.conf import settings
from .models import Scan

from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer,
    Image,
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import cm

import os


def generate_pdf(request):

    scan = Scan.objects.order_by("-created_at").first()

    if not scan:
        return HttpResponse("No scan available.")

    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = 'attachment; filename="Security_Report.pdf"'

    doc = SimpleDocTemplate(
        response,
        rightMargin=40,
        leftMargin=40,
        topMargin=35,
        bottomMargin=35,
    )

    styles = getSampleStyleSheet()
    elements = []

    # ==========================
    # Logo
    # ==========================

    logo_path = os.path.join(
        settings.BASE_DIR,
        "static",
        "images",
        "logo.jpg"
    )

    if os.path.exists(logo_path):

        logo = Image(logo_path)
        logo.drawWidth = 3 * cm
        logo.drawHeight = 3 * cm
        logo.hAlign = "CENTER"

        elements.append(logo)
        elements.append(Spacer(1, 15))

    # ==========================
    # Title
    # ==========================

    title = Paragraph(
        "<b><font size='22'>WEB SECURITY REPORT</font></b>",
        styles["Title"]
    )

    title.alignment = TA_CENTER

    elements.append(title)

    elements.append(Spacer(1, 25))

    # ==========================
    # Table
    # ==========================

    table_data = [
        ["Information", "Value"],
        ["Website", scan.url],
        ["Security Score", f"{scan.score}/100"],
        ["Status Code", str(scan.status_code)],
        ["HTTPS", scan.https],
        ["SSL Certificate", scan.ssl],
        ["Technology", scan.technology],
        ["Response Time", f"{scan.response_time} s"],
        ["Scan Date", scan.created_at.strftime("%d/%m/%Y %H:%M")],
    ]

    table = Table(
        table_data,
        colWidths=[7 * cm, 9 * cm]
    )

    table.setStyle(TableStyle([

        ("BACKGROUND", (0, 0), (-1, 0), colors.white),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.black),

        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 12),

        ("GRID", (0, 0), (-1, -1), 0.6, colors.grey),

        ("BACKGROUND", (0, 1), (0, -1), colors.HexColor("#F5F5F5")),
        ("BACKGROUND", (1, 1), (1, -1), colors.white),

        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),

        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

    ]))

    elements.append(table)

    elements.append(Spacer(1, 25))

    # ==========================
    # Footer
    # ==========================

    footer = Paragraph(
        "<font size='10' color='grey'>Generated by vala </font>",
        styles["Normal"]
    )

    footer.alignment = TA_CENTER

    elements.append(footer)

    # ==========================
    # Build PDF
    # ==========================

    doc.build(elements)

    return response